# config/routes.yaml

home:
    path: /
    controller: App\Controller\HomeController::index
logout:
    path: /logout
    methods: GET
register:
    path: /register
    controller: App\Controller\RegistrationController::register